# Generated by Django 3.2.9 on 2022-05-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RewireApp', '0002_blocklist_friend_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocklist',
            name='website',
            field=models.CharField(max_length=1000),
        ),
    ]
