# Generated by Django 3.2.9 on 2022-05-01 14:19

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RewireApp', '0005_flow_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='end_time',
            field=unixtimestampfield.fields.UnixTimeStampField(),
        ),
        migrations.AlterField(
            model_name='flow',
            name='start_time',
            field=unixtimestampfield.fields.UnixTimeStampField(),
        ),
    ]
