# Generated by Django 3.2.9 on 2022-05-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RewireApp', '0006_auto_20220501_1419'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flow',
            unique_together=set(),
        ),
    ]
